version: "2"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_serv
    ports:
      - "8080:80"
    networks:
      - backend

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth_serv
    networks:
      - backend
    command: gunicorn run:app -b 0.0.0.0:8000

  flights:
    build:
      context: .
      dockerfile: ./flights/Dockerfile
    container_name: flights_serv
    networks:
      - backend
    command: gunicorn run:app -b 0.0.0.0:8000

networks:
  backend:
