language: python
python:
    - "3.7"
install: pip install -r requirements.txt
script:
      - cd homeworks/homework_08_web/homework_07_web
      - py.test --pep8 && pytest --cov
      - cd ../authorization
      - py.test --pep8 && pytest --cov

