# Generated by Django 2.2.4 on 2019-11-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('aircaft_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('flight_time', models.PositiveIntegerField()),
                (
                    'aircraft_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='flights_api.AircraftType'
                    )
                ),
                (
                    'destination_airport',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='flights_api.Airports'
                    )
                ),
            ],
        ),
    ]
