# Generated by Django 2.2.4 on 2019-11-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10)),
                ('request_body', models.CharField(max_length=255)),
                ('request_path', models.CharField(max_length=255)),
                ('request_time', models.FloatField()),
            ],
        ),
    ]
