# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft_type', models.CharField(db_index=True, max_length=30, verbose_name='airport name')),
            ],
            options={
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='AirFlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField(db_index=True, verbose_name='departure time')),
                ('arrival_time', models.DateTimeField(db_index=True, verbose_name='arrival time')),
                ('travel_time', models.TimeField(db_index=True, default=0, verbose_name='travel time')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Aircraft')),
            ],
            options={
                'db_table': 'airflight',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(db_index=True, max_length=30, verbose_name='airport name')),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.AddField(
            model_name='airflight',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airport'),
        ),
    ]
