# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airflight',
            name='travel_time',
            field=models.PositiveIntegerField(db_index=True, verbose_name=b'travel time'),
        ),
    ]
