# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20191106_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name=b'airport name'),
        ),
        migrations.AlterField(
            model_name='airflight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Aircraft', to_field=b'aircraft_type'),
        ),
        migrations.AlterField(
            model_name='airflight',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airport', to_field=b'airport_name'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name=b'airport name'),
        ),
    ]
