# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20191106_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airflight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Aircraft'),
        ),
        migrations.AlterField(
            model_name='airflight',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airport'),
        ),
    ]
