# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20191106_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airflight',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
