# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='AirFlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField(db_index=True, verbose_name=b'departure time')),
                ('arrival_time', models.DateTimeField(db_index=True, verbose_name=b'arrival time')),
                ('travel_time', models.PositiveIntegerField(db_index=True, default=0, verbose_name=b'travel time')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Aircraft', to_field=b'aircraft_type')),
            ],
            options={
                'db_table': 'airflight',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.AddField(
            model_name='airflight',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airport', to_field=b'airport_name'),
        ),
    ]
