# Generated by Django 2.2.6 on 2019-11-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_model', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('airport', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(verbose_name='Departure_time')),
                ('arrival', models.DateTimeField(verbose_name='Arrival_time')),
                ('travel', models.PositiveIntegerField(verbose_name='Travel_time')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Destination')),
            ],
        ),
    ]
