# Generated by Django 2.2.6 on 2019-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=20)),
                ('server_hostname', models.CharField(max_length=255)),
                ('request_path', models.CharField(max_length=255)),
                ('request_body', models.CharField(max_length=255)),
                ('response_status', models.IntegerField(max_length=255)),
                ('response_body', models.CharField(max_length=255)),
                ('run_time', models.FloatField()),
            ],
        ),
    ]
