# Generated by Django 2.2.6 on 2019-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='response_status',
            field=models.IntegerField(),
        ),
    ]
