# Generated by Django 2.2.6 on 2019-11-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20191107_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='request_body',
        ),
    ]
