# Generated by Django 2.2.6 on 2019-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_requestlog_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='request_method',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
