# Generated by Django 2.2.6 on 2019-11-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20191109_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='response_body',
        ),
    ]
